# Generated by Django 6.0 on 2025-12-15 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_emailtemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedemail',
            name='scheduled_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='generatedemail',
            name='status',
            field=models.CharField(default='Draft', max_length=20),
        ),
    ]
