# Generated by Django 6.0 on 2025-12-16 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_generatedemail_scheduled_date_generatedemail_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedemail',
            name='recipient_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
